name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: >
    ${{ github.workflow }} @
    ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.x"
        enable-cache: true
    - name: Install d2
      run: curl -fsSL https://d2lang.com/install.sh | sh -s --
    - name: Install package for testing
      run: uv sync --all-extras
    - name: Run tests
      run: uv run pytest

  typecheck:
    name: Type check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.x"
        enable-cache: true
    - name: Install package for typechecking
      run: uv sync --all-extras
    - name: Run type checker
      run: uv run mypy src/ tests/
